import { useMemo, useState } from "react";
import type { Analysis } from "@signaldesk/contracts";
import { Activity, BarChart3, Check, ChevronDown, CircleGauge, Clock3, FileText, FolderKanban, HelpCircle, LayoutDashboard, Menu, MessageSquareText, Plus, Search, Settings, Sparkles, Users, X } from "lucide-react";
import { feedback } from "./data";

const apiUrl = import.meta.env.VITE_API_URL ?? "http://localhost:8787";
const seeded: Analysis = { id: "run-demo", status: "succeeded", headline: "What customers need next", summary: "Shorten time to value, keep every insight auditable, and make findings effortless to circulate.", themes: [
  { id:"t1", title:"Setup friction is delaying activation", summary:"Onboarding language and import status are unclear for new workspaces.", urgency:"high", trend:"rising", recommendation:"Add a guided import checklist and measure time-to-first-insight.", evidenceIds:["FB-184","FB-168"] },
  { id:"t2", title:"Teams need clearer evidence trails", summary:"Decision-makers want to inspect the source behind generated themes.", urgency:"critical", trend:"rising", recommendation:"Make source excerpts one click away from every generated claim.", evidenceIds:["FB-179"] },
  { id:"t3", title:"Exports are part of the sharing loop", summary:"Stakeholders need a low-friction way to circulate weekly findings.", urgency:"medium", trend:"steady", recommendation:"Ship a branded read-only report before adding more dashboard widgets.", evidenceIds:["FB-171","FB-163"] }
], usage:{items:5,units:38,limit:100},createdAt:"2026-08-08T12:00:00.000Z" };

const nav = [{icon:LayoutDashboard,label:"Overview"},{icon:MessageSquareText,label:"Feedback",count:24},{icon:Sparkles,label:"Analyses"},{icon:Users,label:"Team"},{icon:CircleGauge,label:"Usage"},{icon:Settings,label:"Settings"}];

export function App(){
 const [analysis,setAnalysis]=useState(seeded); const [loading,setLoading]=useState(false); const [open,setOpen]=useState(false); const [mobile,setMobile]=useState(false); const [notice,setNotice]=useState("");
 const evidence=useMemo(()=>Object.fromEntries(feedback.map(item=>[item.id,item])),[]);
 async function runAnalysis(){ setLoading(true); setNotice(""); try { const response=await fetch(`${apiUrl}/v1/analyses`,{method:"POST",headers:{"content-type":"application/json","authorization":"Bearer demo-user"},body:JSON.stringify({projectId:"project-demo",feedback,idempotencyKey:crypto.randomUUID()})}); if(!response.ok) throw new Error(); setAnalysis(await response.json()); setOpen(false); setNotice("Analysis complete — 5 feedback items synthesized."); } catch { setAnalysis(seeded); setOpen(false); setNotice("Demo analysis complete. Start the API to use the live local workflow."); } finally {setLoading(false);} }
 return <div className="app-shell">
  <aside className={`sidebar ${mobile?"mobile-open":""}`}><div className="brand"><span className="brand-mark"/>SignalDesk<button className="close-menu" onClick={()=>setMobile(false)} aria-label="Close navigation"><X/></button></div><div className="workspace"><div className="workspace-avatar">A</div><div><strong>Atlas Labs</strong><small>Product workspace</small></div><ChevronDown size={15}/></div><nav aria-label="Main navigation">{nav.map(({icon:Icon,label,count},i)=><button className={i===0?"active":""} key={label}><Icon size={18}/><span>{label}</span>{count&&<em>{count}</em>}</button>)}</nav><div className="sidebar-foot"><button><HelpCircle size={18}/>Help & resources</button><div className="user"><div className="avatar">RP</div><div><strong>Riley Parker</strong><small>Owner · Pro trial</small></div><button aria-label="Account options"><ChevronDown size={15}/></button></div></div></aside>
  <main><header><button className="menu" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu/></button><div><h1>Customer intelligence</h1><p>Here’s what changed across your feedback this week.</p></div><div className="header-actions"><button className="quiet"><Clock3 size={17}/>Last 7 days<ChevronDown size={15}/></button><button className="primary" onClick={()=>setOpen(true)}><Plus size={17}/>New analysis</button></div></header>
  {notice&&<div className="notice"><Check size={16}/>{notice}</div>}
  <section className="summary"><div><span className="section-label">Weekly synthesis · 24 new signals</span><h2>{analysis.headline}</h2><p>{analysis.summary}</p></div><div className="signal" aria-label="Signal trend"><span>Signal strength</span><strong>+18%</strong><svg viewBox="0 0 220 55"><path d="M2 47 C35 45 37 32 66 36 S105 43 122 23 S165 33 184 15 S205 9 218 3"/></svg></div></section>
  <div className="content-grid"><section className="themes"><div className="section-head"><div><h3>Top themes</h3><p>Grouped from this week’s feedback and ranked by urgency.</p></div><button className="text-button">View all analyses →</button></div>{analysis.themes.map((theme,index)=><article className="theme" key={theme.id}><div className="theme-index">0{index+1}</div><div className="theme-copy"><div className="theme-title"><h4>{theme.title}</h4><span className={`urgency ${theme.urgency}`}>{theme.urgency}</span></div><p>{theme.summary}</p><div className="evidence"><b>Evidence</b>{theme.evidenceIds.map(id=><button key={id} title={evidence[id]?.body}>{id}</button>)}</div></div><div className="trend"><Activity size={15}/><span>{theme.trend}</span></div></article>)}</section>
  <aside className="right-rail"><section className="actions"><div className="section-head"><div><h3>Action queue</h3><p>Recommended next moves</p></div><button aria-label="Add action"><Plus size={18}/></button></div>{analysis.themes.map((theme,index)=><div className="action" key={theme.id}><span className={`priority p${index+1}`}>{index+1}</span><div><strong>{theme.recommendation}</strong><small>{index===0?"Jordan · Growth":index===1?"Mina · Product":"Unassigned"}</small></div></div>)}</section><section className="usage"><div className="usage-head"><div><span>Usage this month</span><strong>{analysis.usage.units}<small> / {analysis.usage.limit} analyses</small></strong></div><CircleGauge/></div><div className="meter"><i style={{width:`${analysis.usage.units}%`}}/></div><p>Resets September 1 · Pro trial</p></section></aside></div>
  <section className="recent"><div className="section-head"><div><h3>Recent feedback</h3><p>The latest customer signals across connected sources.</p></div><button className="quiet"><Search size={16}/>Search feedback</button></div><div className="feedback-list">{feedback.slice(0,3).map(item=><div className="feedback-row" key={item.id}><span className="source-icon">{item.source==="support"?<HelpCircle/>:item.source==="survey"?<FileText/>:<MessageSquareText/>}</span><div><strong>{item.customer}</strong><p>{item.body}</p></div><span className="source">{item.source}</span><time>{item.id}</time></div>)}</div></section>
  </main>
  {open&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setOpen(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="analysis-title" onMouseDown={e=>e.stopPropagation()}><div className="modal-icon"><Sparkles/></div><h2 id="analysis-title">Analyze this week’s feedback</h2><p>SignalDesk will synthesize 5 recent items into evidence-linked themes and recommended actions.</p><div className="analysis-details"><span><FolderKanban/>Atlas product</span><span><MessageSquareText/>5 feedback items</span><span><BarChart3/>About 1 analysis unit</span></div><div className="modal-actions"><button className="quiet" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" onClick={runAnalysis} disabled={loading}>{loading?"Analyzing…":"Run analysis"}</button></div></section></div>}
 </div>
}
